#include "nsISupports.idl"

[scriptable, uuid(9AF36A2F-9B04-4936-ACFC-7BFFA77BC297)]
interface nsINymbleUser : nsISupports
{
  void setPseudonym(in string marshalled_pseudonym);
  string getPseudonym();
  
  void setVerifyKeyN([array, size_is(len)] in PRUint8 bytes, in PRUint32 len);
  
  string addBlacklist(in string marshalled_blacklist);
  boolean addCredential(in string marshalled_credential);
  string getTicket(in string serverId);
};
