#include "nsISupports.idl"

[scriptable, uuid(9AF36A2F-9B04-4936-ACFC-7BFFA77BC297)]
interface INymble : nsISupports
{
	void user_initialize(in string pseudonym, [array, size_is(aLength)] in PRUint8 aArray, in PRUint32 aLength);
	void user_set_certificate([array, size_is(aLength)] in PRUint8 aArray, in PRUint32 aLength);
	string user_pseudonym();
	void user_entry_initialize(in string server_id, in string credential, in unsigned long time_period);
	boolean user_entry_exists(in string server_id);
	string user_credential_get(in string server_id, in unsigned long time_period);
	boolean user_blacklist_update(in string server_id, in string blacklist, in unsigned long link_window, in unsigned long time_period);
	boolean user_blacklist_check(in string server_id);
};

