// Generated by the protocol buffer compiler.  DO NOT EDIT!

#include "nymble_blacklist.pb.h"
#include <google/protobuf/descriptor.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format_inl.h>

namespace Nymble {
namespace Marshal {

namespace {

const ::google::protobuf::Descriptor* Blacklist_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Blacklist_reflection_ = NULL;

}  // namespace


void protobuf_BuildDesc_nymble_5fblacklist_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;
  ::google::protobuf::DescriptorPool* pool =
    ::google::protobuf::DescriptorPool::internal_generated_pool();

  const ::google::protobuf::FileDescriptor* file = pool->InternalBuildGeneratedFile(
    "\n\026nymble_blacklist.proto\022\016Nymble.Marshal"
    "\"\206\001\n\tBlacklist\022\023\n\013link_window\030\001 \002(\005\022\023\n\013t"
    "ime_period\030\002 \002(\005\022\021\n\tserver_id\030\003 \002(\014\022\017\n\007b"
    "l_hash\030\004 \002(\014\022\016\n\006bmac_n\030\005 \002(\014\022\013\n\003sig\030\006 \002("
    "\014\022\016\n\006nymble\030\007 \003(\014", 177);
  Blacklist_descriptor_ = file->message_type(0);
  Blacklist_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      Blacklist_descriptor_,
      &Blacklist::default_instance(),
      Blacklist::_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Blacklist, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Blacklist, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    Blacklist_descriptor_, &Blacklist::default_instance());
}

// Force BuildDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_nymble_5fblacklist_2eproto {
  StaticDescriptorInitializer_nymble_5fblacklist_2eproto() {
    protobuf_BuildDesc_nymble_5fblacklist_2eproto();
  }
} static_descriptor_initializer_nymble_5fblacklist_2eproto_;


// ===================================================================

const Blacklist Blacklist::default_instance_;



const ::std::string Blacklist::_default_server_id_;
const ::std::string Blacklist::_default_bl_hash_;
const ::std::string Blacklist::_default_bmac_n_;
const ::std::string Blacklist::_default_sig_;

const int Blacklist::_offsets_[7] = {
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Blacklist, link_window_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Blacklist, time_period_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Blacklist, server_id_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Blacklist, bl_hash_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Blacklist, bmac_n_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Blacklist, sig_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Blacklist, nymble_),
};

Blacklist::Blacklist()
  : _cached_size_(0),
    link_window_(0),
    time_period_(0),
    server_id_(const_cast< ::std::string*>(&_default_server_id_)),
    bl_hash_(const_cast< ::std::string*>(&_default_bl_hash_)),
    bmac_n_(const_cast< ::std::string*>(&_default_bmac_n_)),
    sig_(const_cast< ::std::string*>(&_default_sig_)) {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  if (this == &default_instance_) {
  }
}

Blacklist::Blacklist(const Blacklist& from)
  : _cached_size_(0),
    link_window_(0),
    time_period_(0),
    server_id_(const_cast< ::std::string*>(&_default_server_id_)),
    bl_hash_(const_cast< ::std::string*>(&_default_bl_hash_)),
    bmac_n_(const_cast< ::std::string*>(&_default_bmac_n_)),
    sig_(const_cast< ::std::string*>(&_default_sig_)) {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  MergeFrom(from);
}

Blacklist::~Blacklist() {
  if (server_id_ != &_default_server_id_) {
    delete server_id_;
  }
  if (bl_hash_ != &_default_bl_hash_) {
    delete bl_hash_;
  }
  if (bmac_n_ != &_default_bmac_n_) {
    delete bmac_n_;
  }
  if (sig_ != &_default_sig_) {
    delete sig_;
  }
  if (this != &default_instance_) {
  }
}

const ::google::protobuf::Descriptor* Blacklist::descriptor() {
  if (Blacklist_descriptor_ == NULL) protobuf_BuildDesc_nymble_5fblacklist_2eproto();
  return Blacklist_descriptor_;
}

Blacklist* Blacklist::New() const {
  return new Blacklist;
}

const ::google::protobuf::Descriptor* Blacklist::GetDescriptor() const {
  return descriptor();
}

const ::google::protobuf::Reflection* Blacklist::GetReflection() const {
  if (Blacklist_reflection_ == NULL) protobuf_BuildDesc_nymble_5fblacklist_2eproto();
  return Blacklist_reflection_;
}

}  // namespace Marshal
}  // namespace Nymble
